routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return redirect()->route('home');
});

Auth::routes();
Route::get('/logout', function () {
    Auth::logout();

    return redirect()->route('login');
})->name('logout');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/clients', 'ClientController');
Route::resource('/logements', 'LogementController');
Route::resource('/typelogements', 'TypeLogementController');
Route::resource('/locations', 'LocationController');
Route::resource('/contrats', 'ContratController');
Route::resource('/configurations', 'ConfigurationController');
Route::resource('/payements', 'PayementController');
Route::resource('/users', 'UserController');
Route::get('/recu/{payement}', 'PayementController@recu')->name('recupdf');
Route::get('/contrat/{location}', 'ContratController@contrat')->name('contratpdf');
Route::get('/locations/{client}', 'ClientController@createLocation')->name('createLocation');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    protected $fillable = [
      'nom',
      'prenom',
      'email',
      'telephone',
      'adresse',
      'age',
      'sexe',
      'personne_a_contacter',
      'numero_a_contacter',
      'piece_identite',
      'profession',
    ];

    public function locations($value='')
    {
      return $this->hasMany('App\Models\Location');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Models\Logement;
use App\Models\Location;
use App\Models\TypeLogement;
use App\Models\Contrat;
use Illuminate\Http\Request;
use PDF;
use Image;
use DateTime;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::all();
        return view('pages.clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = TypeLogement::all();
        $logements = Logement::all();
        return view('pages.clients.create', compact('logements','types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $fdate = $request->date_debut;
      $tdate = $request->date_fin;
      $datetime1 = new DateTime($fdate);
      $datetime2 = new DateTime($tdate);
      $interval = $datetime1->diff($datetime2);
      // dd($interval);
      $photo = $request->file('piece_identite');
        $request->validate([
          'nom'                 => 'required|string|max:60',
          'prenom'              => 'required|string|max:60',
          'adresse'             => 'required|string|max:60',
          'telephone'           => 'required|string|max:60',
        ]);
        $client = Client::create([
          'nom'                    => $request->nom,
          'prenom'                 => $request->prenom,
          'adresse'                => $request->adresse,
          'sexe'                   => $request->sexe,
          'telephone'              => $request->telephone,
          'age'                    => $request->age,
          'piece_identite'         => $request->piece_identite,
          'profession'             => $request->profession,
          'email'                  => $request->email,
          'personne_a_contacter'   => $request->personne_a_contacter,
          'numero_a_contacter'     => $request->numero_a_contacter,
        ]);

        if ($request->file('piece_identite')->isValid()) {
            $avatar = $request->file('piece_identite');
            $filename = time() . '-piece-identite-.' . $request->piece_identite->extension();
            $filename = '/uploads/avatars/' . $filename;
            // dd($filename);
            $location = public_path($filename);
            Image::make($avatar)->save($location);
            $client->piece_identite = $filename;
            $client->save();
        }

        // $img = Image::make($photo)->resize(320, 240)->insert('public/watermark.png');

        $location = Location::create([
          'date_debut'        =>$request->date_debut,
          'date_fin'          =>$request->date_fin,
          'client_id'         =>$client->id,
          'logement_id'       =>$request->logement,
        ]);
        $loge = Logement::where('id', $location->logement->id);
        $loge->update([
          'status'   =>"occupé",
        ]);
        $contrat = Contrat::create([
          'duree'             =>$interval->format('%m mois %d jours'),
          'date'              =>now(),
          'location_id'       =>$location->id,
        ]);


        return redirect()->route('clients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
      // dd($client->piece_identite);
      $locations = Location::where('client_id', $client->id)->latest();
      // dd($locations);
        return view('pages.clients.show', compact('client', 'locations'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('pages.clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();
        return redirect()->route('clients.index');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createLocation(Request $request, $id)
    {
        $client = Client::find($id);
        return view('pages.clients.location', compact('client'));
    }


}

resources/views/pages/clients/create.blade.php
@extends('layouts.app')
@section('title', 'Nouveau Client')
@section('stylesheet')
  <!-- daterange picker -->
    <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <!-- Bootstrap4 Duallistbox -->
    <link rel="stylesheet" href="/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css">
@endsection
@section('content')
  <style media="screen">
    .formulaire div{
      margin: auto;
      justify-content: center;
    }
    .button button, .button a{
      margin: auto;
      margin-top: 50px;
      margin-bottom: 50px;
    }
    .card-header h1{
      font-family: 'Roboto', sans-serif;
      font-weight: lighter;
      text-transform: uppercase;
      font-size: 30px;
      text-align: center;
    }
    .subtitle{
      font-family: 'Roboto', sans-serif;
      font-weight: lighter;
      text-transform: uppercase;
      font-size: 20px;
      text-align: center;
    }
  </style>
  <div class="">
    <nav aria-label="breadcrumb" style="height:50px;">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('home')}}">Acceuil</a></li>
        <li class="breadcrumb-item"><a href="{{route('clients.index')}}">Clients</a> </li>
        <li class="breadcrumb-item active" aria-current="page">Nouveau Client</li>
      </ol>
    </nav>
  </div>
  <div class="card">
    <div class="card-header">
      <h1>Nouveau Client</h1>
    </div>
    <div class="card-body">
      <form class="" action="{{route('clients.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="card card-danger">
          <div class="card-body formulaire">
            <br>
            <h2 class="subtitle">Les Informations du Client</h2>
            <br>
            <div class="row col-11">
              <div class="col-3">
                <label for="">Nom</label>
                <input name="nom" id="nom" type="text" class="form-control" placeholder="Entrez le nom">
              </div>
              <div class="col-3">
                <label for="">Prénom</label>
                <input name="prenom" id="prenom" type="text" class="form-control" placeholder="Entrez le prenom">
              </div>
              <div class="col-3">
                <label for="">Téléphone</label>
                <input name="telephone" id="telephone" type="text" class="form-control" placeholder="Entrez le numéro">
              </div>
            </div>
            <br>
            <div class="row col-11">
              <div class="col-3">
                <label for="">Adresse</label>
                <input name="adresse" id="adresse" type="text" class="form-control" placeholder="Entrez l'adresse">
              </div>
              <div class="col-3">
                <div class="form-group">
                  <label>Sexe</label>
                  <select class="custom-select" name="sexe" id="sexe">
                    <option value="null" selected disabled>-- Selectionner --</option>
                    <option value="masculin">Masculin</option>
                    <option value="feminin">Feminin</option>
                  </select>
                </div>
              </div>
              <div class="col-3">
                <label for="">Age</label>
                <input name="age" type="number" id="age" class="form-control" placeholder="Entrez l'age">
              </div>
            </div>
            <br>
            <br>
            <div class="row col-11">
              <div class="col-3">
                <div class="form-group">
                  <label for="myfile">Piece d'identité</label>
                  <input type="file" id="piece_identite" name="piece_identite">
                </div>
              </div>
              <div class="col-3">
                <label for="">Profession</label>
                <input name="profession" type="text" id="profession" class="form-control" placeholder="Entrez la profession">
              </div>
              <div class="col-3">
                <label for="">Email <i style="color:red">*</i> </label>
                <input name="email" type="email" id="email" class="form-control" placeholder="Entrez l'email">
              </div>
            </div>
            <br>
            <div class="row col-11">
              <div class="col-3">
                <div class="form-group">
                  <label>Personne à Contacter</label>
                  <input name="personne_a_contacter" type="text" id="personne_a_contacter" class="form-control" placeholder="Entrez le nom et prenom">
                </div>
              </div>
              <div class="col-3">
                <label for="">Numero de la personne</label>
                <input name="numero_a_contacter" type="text" id="numero_a_contacter" class="form-control" placeholder="Entrez le numéro">
              </div>
              <div class="col-3">

              </div>
            </div>
            <hr>
            <h2 class="subtitle">Informations de la location</h2>
            <br>
            <div class="row col-11">
                <div class="col-3">
                  <label>Type Local</label>
                  <select class="form-control" name="type">
                    <option value="0" selected disabled>--- Selectionner un type ---</option>
                    @foreach ($types as $type)
                      <option value="{{$type->id}}">{{$type->nom}}</option>
                    @endforeach
                  </select>
                </div>

                <div class="col-3">
                  <label>Local</label>
                  <select class="form-control" name="logement">
                    <option value="0" selected disabled>--- Selectionner un local ---</option>
                    {{-- @foreach ($logements as $logement)
                      <option value="{{$logement->id}}">{{$logement->code}}({{$logement->status}})</option>
                    @endforeach --}}
                  </select>
                </div>
              </div>
              <br>
              <div class="row col-11">

                <div class="col-3">
                  <label>Date de début</label>
                  <input type="date" name="date_debut" class="form-control">
                </div>
                <div class="col-3">
                  <label>Date de fin</label>
                  <input type="date" name="date_fin" class="form-control">
                </div>
              </div>
              <br>
              <div class="row col-11">
                <div class="col-3">
                  <label>Nombre de mois</label>
                  <input type="number" name="number" class="form-control">
                </div>
                <div class="col-3">
                  <label>Caution</label>
                  <input type="text" name="caution" class="form-control" readonly>
                </div>
            </div>
            <br>
            <div class="row col-6 button">
              <a class="btn btn-danger" href="{{route('clients.index')}}">Annuler</a>
              <button class="btn btn-primary" type="submit">Ajouter</button>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </form>
    </div>
  </div>
@endsection
@section('script')
  <script src="/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
  <!-- Select2 -->
<script src="/plugins/select2/js/select2.full.min.js"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
<!-- InputMask -->
<script src="/plugins/moment/moment.min.js"></script>
<script src="/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
<!-- date-range-picker -->
<script src="/plugins/daterangepicker/daterangepicker.js"></script>
<!-- bootstrap color picker -->
<script src="/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
      theme: 'bootstrap4'
    })

    //Datemask dd/mm/yyyy
    $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
    //Datemask2 mm/dd/yyyy
    $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
    //Money Euro
    $('[data-mask]').inputmask()

    //Date range picker
    $('#reservation').daterangepicker()
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({
      timePicker: true,
      timePickerIncrement: 30,
      locale: {
        format: 'MM/DD/YYYY hh:mm A'
      }
    })
    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
      }
    )

    //Timepicker
    $('#timepicker').datetimepicker({
      format: 'LT'
    })

    //Bootstrap Duallistbox
    $('.duallistbox').bootstrapDualListbox()

    //Colorpicker
    $('.my-colorpicker1').colorpicker()
    //color picker with addon
    $('.my-colorpicker2').colorpicker()

    $('.my-colorpicker2').on('colorpickerChange', function(event) {
      $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
    });

    $("input[data-bootstrap-switch]").each(function(){
      $(this).bootstrapSwitch('state', $(this).prop('checked'));
    });

  })
//   function myFunction() {
//
//   var x = document.getElementById("fname");
//   x.value = x.value.toUpperCase();
// }

$(document).ready(function(){
  $("select[name='type']").change(function () {
            var type_id = $(this).val();
            console.log(type_id);

            if (type_id) {
                $.ajax({
                    url: "{{ route('api.logements') }}?type="+type_id,
                    type: "GET",
                    dataType: "json",
                    success: function(data) {
                        console.log(data);
                        $("select[name='logement']").empty();
                        $("select[name='logement']").append('<option>--- Local ---</option>')
                        $.each(data, function (key, value) {
                            console.log(key);
                            $("select[name='logement']").append('<option value="'+key+'">'+value+'</option>')
                        });
                    }
                });
            } else {
                $("select[name='logement']").empty();
            }
            });

});
</script>
@endsection

resources/views/pages/clients/edit.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  </head>
  <body>
<style media="screen">
  .formulaire div{
    margin: auto;
    justify-content: center;
  }
  .button button, .button a{
    margin: auto;
    margin-top: 50px;
    margin-bottom: 50px;
  }
  .card-header h1{
    font-family: 'Roboto', sans-serif;
    font-weight: lighter;
    text-transform: uppercase;
    font-size: 30px;
    text-align: center;
  }
  .subtitle{
    font-family: 'Roboto', sans-serif;
    font-weight: lighter;
    text-transform: uppercase;
    font-size: 20px;
    text-align: center;
  }
</style>

<div class="card">
  <div class="card-header">
    <h1>Modification</h1>
  </div>
  <div class="card-body">
    <form class="" action="{{route('clients.update', $client)}}" method="post">
      @csrf
      <div class="card card-danger">
        <div class="card-body formulaire">
          <br>
          <h2 class="subtitle">Les Informations de {{$client->nom}} {{$client->prenom}}</h2>
          <br>
          <div class="row col-11">
            <div class="col-3">
              <label for="">Nom</label>
              <input name="nom" id="nom" type="text" class="form-control" placeholder="Entrez le nom" value="{{$client->nom}}">
            </div>
            <div class="col-3">
              <label for="">Prénom</label>
              <input name="prenom" id="prenom" type="text" class="form-control" placeholder="Entrez le prenom" value="{{$client->prenom}}">
            </div>
            <div class="col-3">
              <label for="">Téléphone</label>
              <input name="telephone" id="telephone" type="text" class="form-control" placeholder="Entrez le numéro" value="{{$client->telephone}}">
            </div>
          </div>
          <br>
          <div class="row col-11">
            <div class="col-3">
              <label for="">Adresse</label>
              <input name="adresse" id="adresse" type="text" class="form-control" placeholder="Entrez l'adresse" value="{{$client->adresse}}">
            </div>
            <div class="col-3">
              <div class="form-group">
                <label>Sexe</label>
                <select class="custom-select" name="sexe" id="sexe">
                  @if ($client->sexe == "masculin")
                    <option value="{{$client->sexe}}" selected>Masculin</option>
                  @elseif ($client->sexe == "feminin")
                    <option value="{{$client->sexe}}" selected>Féminin</option>
                  @endif
                  <option value="masculin">Masculin</option>
                  <option value="feminin">Feminin</option>
                </select>
              </div>
            </div>
            <div class="col-3">
              <label for="">Age</label>
              <input name="age" type="number" id="age" class="form-control" placeholder="Entrez l'age" value="{{$client->age}}">
            </div>
          </div>
          <br>
          <br>
          <div class="row col-11">
            <div class="col-3">
              <div class="form-group">
                <label for="myfile">Piece d'identité</label>
                <input type="file" id="piece_identite" name="piece_identite" value="{{$client->piece_identite}}">
              </div>
            </div>
            <div class="col-3">
              <label for="">Profession</label>
              <input name="profession" type="text" id="profession" class="form-control" placeholder="Entrez la profession" value="{{$client->profession}}">
            </div>
            <div class="col-3">
              <label for="">Email <i style="color:red">*</i> </label>
              <input name="email" type="email" id="email" class="form-control" placeholder="Entrez l'email" value="{{$client->email ?? ' '}}">
            </div>
          </div>
          <br>
          <div class="row col-11">
            <div class="col-3">
              <div class="form-group">
                <label>Personne à Contacter</label>
                <input name="personne_a_contacter" type="text" id="personne_a_contacter" class="form-control" placeholder="Entrez le nom et prenom" value="{{$client->personne_a_contacter}}">
              </div>
            </div>
            <div class="col-3">
              <label for="">Numero de la personne</label>
              <input name="numero_a_contacter" type="text" id="numero_a_contacter" class="form-control" placeholder="Entrez le numéro" value="{{$client->numero_a_contacter}}">
            </div>
            <div class="col-3">

            </div>
          </div>
          </div>
          </div>
          </div>
          </div>
</body>
</html>

resources/views/pages/clients/location.blade.php
Bonjour {{$client->nom}}.

resources/views/pages/clients/show.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  </head>
  <body>
    <style media="screen">
      .actions {
        list-style: none;
      }
      .actions li{
        margin-bottom: 5px;
        width: 100%;
      }
      .historique{
        margin-top: 20px;
      }
      .historique h2{
        font-family: 'Roboto', sans-serif;
        font-weight: lighter;
        text-transform: uppercase;
        font-size: 20px;
        text-align: center;
      }
    </style>
    <div class="row">
      <div class="card col-4">
         <div class="card-body">
             <img src="{{ $client->piece_identite }}" alt="" width="300" height="400">

         </div>
      </div>
      <div class="col-4">
        <h3>Informations Personnelles</h3>
        <p>Nom: <strong>{{$client->nom}}</strong></p>
        <p>Prenom: <strong>{{$client->prenom}}</strong></p>
        <p>Age: <strong>{{$client->age}}</strong></p>
        <p>Sexe: <strong>{{$client->sexe}}</strong></p>
        <p>Profession: <strong>{{$client->profession}}</strong></p>
        <hr>
        <h3>Coordonnéess</h3>
        <p>Adresse: <strong>{{$client->adresse}}</strong></p>
        <p>Téléphone: <strong>{{$client->telephone}}</strong></p>
        <p>Email: <strong>{{$client->email}}</strong></p>
      </div>
      <div class="col-4">
        <ul  class="col actions">
          <li><a class="btn btn-primary" href="{{route('clients.edit', $client)}}"><i class="fa fa-edit"></i> Modifier</a></li>
          <li>
            <a class="btn btn-default" href="{{route('createLocation', $client->id)}}"><i class="fa fa-house"></i> Nouvelle location</a>
          {{-- <form class="" action="{{route('createLocation', $client->id)}}" method="get">
            @csrf
            <button type="button" name="button">Nouvelle Location</button>
          </form> --}}
          </li>
          <li><a class="btn btn-default" href="{{route('payements.create')}}"><i class="fa fa-coins"></i> Nouveau payement</a></li>
        </ul>

        <form action="{{ route('clients.destroy', $client) }}" method="POST">
            @csrf
            {{ method_field('DELETE') }}
            <button type="submit" class="btn btn-oblong btn-outline-danger btn-big">Supprimer</a>
        </form>
      </div>

    </div>
    <div class="historique">
      <h2>Historique de location</h2>
      <table class="table ">
        <thead>
          <tr>
            <th>Numéro</th>
            <th>Date début</th>
            <th>Date fin</th>
            <th>Logement</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($client->locations as $location)
            <tr>
              <td>{{$location->id}}</td>
              <td>{{$location->date_debut}}</td>
              <td>{{$location->date_fin}}</td>
              <td>{{$location->logement->code}}</td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>



    <script src="/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="/dist/js/demo.js"></script>

    <!-- PAGE PLUGINS -->
    <!-- jQuery Mapael -->
    <script src="/plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
    <script src="/plugins/raphael/raphael.min.js"></script>
    <script src="/plugins/jquery-mapael/jquery.mapael.min.js"></script>
    <script src="/plugins/jquery-mapael/maps/usa_states.min.js"></script>
    <!-- ChartJS -->
    <script src="/plugins/chart.js/Chart.min.js"></script>

    <!-- PAGE SCRIPTS -->
    <script src="/dist/js/pages/dashboard2.js"></script>
  </body>
</html>