routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return redirect()->route('home');
});

Auth::routes();
Route::get('/logout', function () {
    Auth::logout();

    return redirect()->route('login');
})->name('logout');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/clients', 'ClientController');
Route::resource('/logements', 'LogementController');
Route::resource('/typelogements', 'TypeLogementController');
Route::resource('/locations', 'LocationController');
Route::resource('/contrats', 'ContratController');
Route::resource('/configurations', 'ConfigurationController');
Route::resource('/payements', 'PayementController');
Route::resource('/users', 'UserController');
Route::get('/recu/{payement}', 'PayementController@recu')->name('recupdf');
Route::get('/contrat/{location}', 'ContratController@contrat')->name('contratpdf');
Route::get('/locations/{client}', 'ClientController@createLocation')->name('createLocation');

app/Models/Configuration.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Configuration extends Model
{
    use HasFactory;
    protected $fillable = [
      'nom',
      'adresse',
      'email',
      'telephone',
      'logo',
    ];
}

app/Http/Controllers/ConfigurationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Configuration;
use Illuminate\Http\Request;

class ConfigurationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $configurations = Configuration::all();
        return view('pages.configurations.index', compact('configurations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.configurations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
          'nom'     => 'required',
          'adresse'     => 'required',
          'email'     => 'required',
          'telephone'     => 'required',
        ]);

        $configuration = Configuration::create([
          'nom'      => $request->nom,
          'adresse'      => $request->nom,
          'email'      => $request->nom,
          'telephone'      => $request->nom,
          'logo'      => $request->nom,
        ]);

        return redirect()->route('configurations.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Configuration  $configuration
     * @return \Illuminate\Http\Response
     */
    public function show(Configuration $configuration)
    {
        return view('pages.configurations.show', compact('configuration'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Configuration  $configuration
     * @return \Illuminate\Http\Response
     */
    public function edit(Configuration $configuration)
    {
      return view('pages.configurations.edit', compact('configuration'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Configuration  $configuration
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Configuration $configuration)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Configuration  $configuration
     * @return \Illuminate\Http\Response
     */
    public function destroy(Configuration $configuration)
    {
        $configuration->delete();
        return redirect()->route('configurations.index');
    }
}

resources/views/pages/configurations/create.blade.php
@extends('layouts.app')
@section('title', 'Nouvelle Configuration')
@section('stylesheet')
  <!-- daterange picker -->
    <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <!-- Bootstrap4 Duallistbox -->
    <link rel="stylesheet" href="/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css">
@endsection
@section('content')
  <style media="screen">
    .formulaire div{
      margin: auto;
      justify-content: center;
    }
    .button button{
      margin: auto;
      margin-top: 50px;
      margin-bottom: 50px;
    }
    .card-header h1{
      font-family: 'Roboto', sans-serif;
      font-weight: lighter;
      text-transform: uppercase;
      font-size: 30px;
      text-align: center;
    }
  </style>
  <div class="">
    <nav aria-label="breadcrumb" style="height:50px;">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('home')}}">Acceuil</a></li>
        <li class="breadcrumb-item"><a href="{{route('configurations.index')}}">Configurations</a> </li>
        <li class="breadcrumb-item active" aria-current="page">Nouvelle Configuration</li>
      </ol>
    </nav>
  </div>
  <div class="card">
    <div class="card-header">
      <h1>Nouvelle Configuration</h1>
    </div>
    <div class="card-body">
      <form class="" action="{{route('configurations.store')}}" method="post">
        @csrf
        <div class="card card-danger">
          <div class="card-body formulaire">
            <div class="row col-11">
              <div class="col-3" style="margin-left:0px">
                <label for="">Nom</label>
                <input name="nom" id="nom" type="text" class="form-control" placeholder="Entrez le nom">
              </div>
              <div class="col-3" style="margin-left:0px">
                <label for="">Adresse</label>
                <input name="adresse" id="adresse" type="text" class="form-control" placeholder="Entrez l'adresse">
              </div>
              <div class="col-3" style="margin-left:0px">
                <label for="">Email</label>
                <input name="email" id="email" type="text" class="form-control" placeholder="Entrez l'email">
              </div>
            </div>
            <br>
            <div class="row col-11">
              <div class="col-3" style="margin-left:0px">
                <label for="">Téléphone</label>
                <input name="telephone" id="telephone" type="text" class="form-control" placeholder="Entrez le numéro">
              </div>
              <div class="col-3" style="margin-left:0px">
                  <label for="myfile">Logo</label>
                  <input type="file" id="myfile" name="logo">
              </div>
              <div class="col-3">

              </div>
            </div>
            <br>
            <div class="row col-6 button">
              <button class="btn btn-danger" type="reset" name="button" value="Annuler">Annuler</button>
              <button class="btn btn-primary" type="submit">Ajouter</button>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      </form>
    </div>
  </div>
@endsection
@section('script')
  <script src="/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
  <!-- Select2 -->
<script src="/plugins/select2/js/select2.full.min.js"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
<!-- InputMask -->
<script src="/plugins/moment/moment.min.js"></script>
<script src="/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>
<!-- date-range-picker -->
<script src="/plugins/daterangepicker/daterangepicker.js"></script>
<!-- bootstrap color picker -->
<script src="/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
      theme: 'bootstrap4'
    })

    //Datemask dd/mm/yyyy
    $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
    //Datemask2 mm/dd/yyyy
    $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
    //Money Euro
    $('[data-mask]').inputmask()

    //Date range picker
    $('#reservation').daterangepicker()
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({
      timePicker: true,
      timePickerIncrement: 30,
      locale: {
        format: 'MM/DD/YYYY hh:mm A'
      }
    })
    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
      }
    )

    //Timepicker
    $('#timepicker').datetimepicker({
      format: 'LT'
    })

    //Bootstrap Duallistbox
    $('.duallistbox').bootstrapDualListbox()

    //Colorpicker
    $('.my-colorpicker1').colorpicker()
    //color picker with addon
    $('.my-colorpicker2').colorpicker()

    $('.my-colorpicker2').on('colorpickerChange', function(event) {
      $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
    });

    $("input[data-bootstrap-switch]").each(function(){
      $(this).bootstrapSwitch('state', $(this).prop('checked'));
    });

  })
</script>
@endsection

resources/views/pages/configurations/index.blade.php
@extends('layouts.app')
@section('title', 'Configurations')
@section('stylesheet')
  <link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
@endsection
@section('content')
  <style media="screen">
  ol li a{
    font-size: 25px;
  }
  .actions{
    display: flex;
    flex-direction: row;
  }
  .actions li{
    list-style: none;
    margin-right: 5px;
  }
  .card-title {
    font-family: 'Roboto', sans-serif;
    font-weight: lighter;
    text-transform: uppercase;
    font-size: 30px;
  }
  </style>
  <div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" height="1000" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
            <iframe name="content" class="embed-responsive-item" allowfullscreen></iframe>
        </div>
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Fermer</button>
      </div>

    </div>
  </div>
</div>
  <div class="">
    <nav aria-label="breadcrumb" style="height:50px;">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('home')}}">Acceuil</a></li>
        <li class="breadcrumb-item active" aria-current="page">Configuration</li>
      </ol>
    </nav>
  </div>
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Configurations</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Numéro</th>
            <th>Nom</th>
            <th>Adresse</th>
            <th>Email</th>
            <th>Téléphone</th>
            <th>Logo</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          @foreach ($configurations as $configuration)
            <tr>
              <td>{{$configuration->id}}</td>
              <td>{{$configuration->nom}}</td>
              <td>{{$configuration->adresse}}</td>
              <td>{{$configuration->email}}</td>
              <td>{{$configuration->telephone}}</td>
              <td>{{$configuration->logo}}</td>
              <td data-toggle="modal" data-target="#exampleModal">
                <ul  class="row actions">
                  <li ><a class="btn btn-default" href="{{route('clients.show', $configuration)}}" target="content"><i class="fa fa-eye"></i> Voir</a></li>
                  <li><a class="btn btn-primary" href="{{route('clients.edit', $configuration)}}"><i class="fa fa-edit"></i> Modifier</a></li>
                  <li><a class="btn btn-danger" href="{{route('clients.destroy', $configuration)}}"><i class="fa fa-trash"></i> Supprimer</a></li>
                </ul>
              </td>
            </tr>
          @endforeach
        </tbody>
        <tfoot>
          <tr>
            <th>Numéro</th>
            <th>Nom</th>
            <th>Adresse</th>
            <th>Email</th>
            <th>Téléphone</th>
            <th>Logo</th>
            <th></th>
          </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>
@endsection
@section('script')
  <script src="/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/dist/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/dist/js/demo.js"></script>
  <!-- page script -->
  <script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@endsection